/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrabajadoresRouteImport } from './routes/_authenticated/trabajadores'
import { Route as AuthenticatedRiesgosRouteImport } from './routes/_authenticated/riesgos'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedJornadaRouteImport } from './routes/_authenticated/jornada'
import { Route as AuthenticatedInspeccionesRouteImport } from './routes/_authenticated/inspecciones'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedIncidentesRouteImport } from './routes/_authenticated/incidentes'
import { Route as AuthenticatedExamenesRouteImport } from './routes/_authenticated/examenes'
import { Route as AuthenticatedEppRouteImport } from './routes/_authenticated/epp'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedEmergenciasRouteImport } from './routes/_authenticated/emergencias'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComitesRouteImport } from './routes/_authenticated/comites'
import { Route as AuthenticatedCapacitacionesRouteImport } from './routes/_authenticated/capacitaciones'
import { Route as AuthenticatedAutoevaluacionRouteImport } from './routes/_authenticated/autoevaluacion'
import { Route as AuthenticatedAprobacionesRouteImport } from './routes/_authenticated/aprobaciones'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrabajadoresRoute =
  AuthenticatedTrabajadoresRouteImport.update({
    id: '/trabajadores',
    path: '/trabajadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRiesgosRoute = AuthenticatedRiesgosRouteImport.update({
  id: '/riesgos',
  path: '/riesgos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJornadaRoute = AuthenticatedJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInspeccionesRoute =
  AuthenticatedInspeccionesRouteImport.update({
    id: '/inspecciones',
    path: '/inspecciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncidentesRoute = AuthenticatedIncidentesRouteImport.update({
  id: '/incidentes',
  path: '/incidentes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamenesRoute = AuthenticatedExamenesRouteImport.update({
  id: '/examenes',
  path: '/examenes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEppRoute = AuthenticatedEppRouteImport.update({
  id: '/epp',
  path: '/epp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmergenciasRoute =
  AuthenticatedEmergenciasRouteImport.update({
    id: '/emergencias',
    path: '/emergencias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComitesRoute = AuthenticatedComitesRouteImport.update({
  id: '/comites',
  path: '/comites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCapacitacionesRoute =
  AuthenticatedCapacitacionesRouteImport.update({
    id: '/capacitaciones',
    path: '/capacitaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAutoevaluacionRoute =
  AuthenticatedAutoevaluacionRouteImport.update({
    id: '/autoevaluacion',
    path: '/autoevaluacion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAprobacionesRoute =
  AuthenticatedAprobacionesRouteImport.update({
    id: '/aprobaciones',
    path: '/aprobaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aprobaciones': typeof AuthenticatedAprobacionesRoute
  '/autoevaluacion': typeof AuthenticatedAutoevaluacionRoute
  '/capacitaciones': typeof AuthenticatedCapacitacionesRoute
  '/comites': typeof AuthenticatedComitesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/emergencias': typeof AuthenticatedEmergenciasRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/epp': typeof AuthenticatedEppRoute
  '/examenes': typeof AuthenticatedExamenesRoute
  '/incidentes': typeof AuthenticatedIncidentesRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/inspecciones': typeof AuthenticatedInspeccionesRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/riesgos': typeof AuthenticatedRiesgosRoute
  '/trabajadores': typeof AuthenticatedTrabajadoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aprobaciones': typeof AuthenticatedAprobacionesRoute
  '/autoevaluacion': typeof AuthenticatedAutoevaluacionRoute
  '/capacitaciones': typeof AuthenticatedCapacitacionesRoute
  '/comites': typeof AuthenticatedComitesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/emergencias': typeof AuthenticatedEmergenciasRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/epp': typeof AuthenticatedEppRoute
  '/examenes': typeof AuthenticatedExamenesRoute
  '/incidentes': typeof AuthenticatedIncidentesRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/inspecciones': typeof AuthenticatedInspeccionesRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/riesgos': typeof AuthenticatedRiesgosRoute
  '/trabajadores': typeof AuthenticatedTrabajadoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/aprobaciones': typeof AuthenticatedAprobacionesRoute
  '/_authenticated/autoevaluacion': typeof AuthenticatedAutoevaluacionRoute
  '/_authenticated/capacitaciones': typeof AuthenticatedCapacitacionesRoute
  '/_authenticated/comites': typeof AuthenticatedComitesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/emergencias': typeof AuthenticatedEmergenciasRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/epp': typeof AuthenticatedEppRoute
  '/_authenticated/examenes': typeof AuthenticatedExamenesRoute
  '/_authenticated/incidentes': typeof AuthenticatedIncidentesRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/inspecciones': typeof AuthenticatedInspeccionesRoute
  '/_authenticated/jornada': typeof AuthenticatedJornadaRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/riesgos': typeof AuthenticatedRiesgosRoute
  '/_authenticated/trabajadores': typeof AuthenticatedTrabajadoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aprobaciones'
    | '/autoevaluacion'
    | '/capacitaciones'
    | '/comites'
    | '/dashboard'
    | '/documentos'
    | '/emergencias'
    | '/empresas'
    | '/epp'
    | '/examenes'
    | '/incidentes'
    | '/indicadores'
    | '/inspecciones'
    | '/jornada'
    | '/reportes'
    | '/riesgos'
    | '/trabajadores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aprobaciones'
    | '/autoevaluacion'
    | '/capacitaciones'
    | '/comites'
    | '/dashboard'
    | '/documentos'
    | '/emergencias'
    | '/empresas'
    | '/epp'
    | '/examenes'
    | '/incidentes'
    | '/indicadores'
    | '/inspecciones'
    | '/jornada'
    | '/reportes'
    | '/riesgos'
    | '/trabajadores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/aprobaciones'
    | '/_authenticated/autoevaluacion'
    | '/_authenticated/capacitaciones'
    | '/_authenticated/comites'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/emergencias'
    | '/_authenticated/empresas'
    | '/_authenticated/epp'
    | '/_authenticated/examenes'
    | '/_authenticated/incidentes'
    | '/_authenticated/indicadores'
    | '/_authenticated/inspecciones'
    | '/_authenticated/jornada'
    | '/_authenticated/reportes'
    | '/_authenticated/riesgos'
    | '/_authenticated/trabajadores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trabajadores': {
      id: '/_authenticated/trabajadores'
      path: '/trabajadores'
      fullPath: '/trabajadores'
      preLoaderRoute: typeof AuthenticatedTrabajadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/riesgos': {
      id: '/_authenticated/riesgos'
      path: '/riesgos'
      fullPath: '/riesgos'
      preLoaderRoute: typeof AuthenticatedRiesgosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jornada': {
      id: '/_authenticated/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof AuthenticatedJornadaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspecciones': {
      id: '/_authenticated/inspecciones'
      path: '/inspecciones'
      fullPath: '/inspecciones'
      preLoaderRoute: typeof AuthenticatedInspeccionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidentes': {
      id: '/_authenticated/incidentes'
      path: '/incidentes'
      fullPath: '/incidentes'
      preLoaderRoute: typeof AuthenticatedIncidentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/examenes': {
      id: '/_authenticated/examenes'
      path: '/examenes'
      fullPath: '/examenes'
      preLoaderRoute: typeof AuthenticatedExamenesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/epp': {
      id: '/_authenticated/epp'
      path: '/epp'
      fullPath: '/epp'
      preLoaderRoute: typeof AuthenticatedEppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emergencias': {
      id: '/_authenticated/emergencias'
      path: '/emergencias'
      fullPath: '/emergencias'
      preLoaderRoute: typeof AuthenticatedEmergenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comites': {
      id: '/_authenticated/comites'
      path: '/comites'
      fullPath: '/comites'
      preLoaderRoute: typeof AuthenticatedComitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capacitaciones': {
      id: '/_authenticated/capacitaciones'
      path: '/capacitaciones'
      fullPath: '/capacitaciones'
      preLoaderRoute: typeof AuthenticatedCapacitacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/autoevaluacion': {
      id: '/_authenticated/autoevaluacion'
      path: '/autoevaluacion'
      fullPath: '/autoevaluacion'
      preLoaderRoute: typeof AuthenticatedAutoevaluacionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aprobaciones': {
      id: '/_authenticated/aprobaciones'
      path: '/aprobaciones'
      fullPath: '/aprobaciones'
      preLoaderRoute: typeof AuthenticatedAprobacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAprobacionesRoute: typeof AuthenticatedAprobacionesRoute
  AuthenticatedAutoevaluacionRoute: typeof AuthenticatedAutoevaluacionRoute
  AuthenticatedCapacitacionesRoute: typeof AuthenticatedCapacitacionesRoute
  AuthenticatedComitesRoute: typeof AuthenticatedComitesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEmergenciasRoute: typeof AuthenticatedEmergenciasRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedEppRoute: typeof AuthenticatedEppRoute
  AuthenticatedExamenesRoute: typeof AuthenticatedExamenesRoute
  AuthenticatedIncidentesRoute: typeof AuthenticatedIncidentesRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedInspeccionesRoute: typeof AuthenticatedInspeccionesRoute
  AuthenticatedJornadaRoute: typeof AuthenticatedJornadaRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedRiesgosRoute: typeof AuthenticatedRiesgosRoute
  AuthenticatedTrabajadoresRoute: typeof AuthenticatedTrabajadoresRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAprobacionesRoute: AuthenticatedAprobacionesRoute,
  AuthenticatedAutoevaluacionRoute: AuthenticatedAutoevaluacionRoute,
  AuthenticatedCapacitacionesRoute: AuthenticatedCapacitacionesRoute,
  AuthenticatedComitesRoute: AuthenticatedComitesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEmergenciasRoute: AuthenticatedEmergenciasRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedEppRoute: AuthenticatedEppRoute,
  AuthenticatedExamenesRoute: AuthenticatedExamenesRoute,
  AuthenticatedIncidentesRoute: AuthenticatedIncidentesRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedInspeccionesRoute: AuthenticatedInspeccionesRoute,
  AuthenticatedJornadaRoute: AuthenticatedJornadaRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedRiesgosRoute: AuthenticatedRiesgosRoute,
  AuthenticatedTrabajadoresRoute: AuthenticatedTrabajadoresRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
